root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = true
  poll=true
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"